//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
MIT QueueB 2026-2026
*/

// Code generated by validation-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *runtime.Scheme) error {
	return nil
}
